openapi: 3.0.0
info:
  title: leader server
  version: 0.1.0

paths:
  /:
    get:
      summary: Get Root
      operationId: getRoot
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "leader"
  /core:
    get:
      summary: Get Root
      operationId: getRoot
      tags:
        - core
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "leader"